# Generated by Django 6.0.5 on 2026-05-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrctor', '0002_category_course_instructorprofile_module_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='instructor_profile',
            field=models.ImageField(default='', upload_to='Instructor_picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Instructor', 'Instructor')], default='Student', max_length=50),
        ),
    ]
