# Generated by Django 6.0.5 on 2026-05-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrctor', '0003_alter_instructorprofile_instructor_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='instructor_profile',
            field=models.ImageField(default='profile.jpg', upload_to='Instructor_picture'),
        ),
    ]
