# Generated by Django 6.0.5 on 2026-05-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrctor', '0004_alter_instructorprofile_instructor_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order_number']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order_number']},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_picture',
            field=models.ImageField(upload_to='Course_picture'),
        ),
    ]
